<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1N3fqnx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1N3fqnx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1N3fqnx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1N3fqnx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1N3fqnx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1N3fqnx',
    'container.build_id' => '3edbbd95',
    'container.build_time' => 1584106188,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1N3fqnx');
